In [46]:
import matplotlib.pyplot as plt
%matplotlib inline
from scipy.io import loadmat
import pandas as pd
import numpy as np
import copy

In [47]:
data=loadmat("E:\Python\PracticleData\data5.mat")

In [48]:
type(data)

dict

In [49]:
#data

In [50]:
X=data['X']
y=data['y']

In [51]:
type(X),type(y)

(numpy.ndarray, numpy.ndarray)

In [52]:
X=np.insert(X,0,1,axis=1)

In [53]:
X=np.matrix(X)
y=np.matrix(y)
theta=np.matrix(np.zeros((1,401)))

In [54]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [55]:
def computeCost(X,y,theta):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y) 
    first = np.multiply(-y,np.log(sigmoid(X*theta.T)))
    second = np.multiply((1-y),np.log(1-sigmoid(X*theta.T)))
    return np.sum(first-second)/len(X)
    

In [56]:
c=computeCost(X,y,theta)

In [57]:
c

-17.051420641774662

In [58]:
def gradientDescent(X,y,theta,alpha, iterations):
    temp = np.matrix(np.zeros((1,401)))
    parameters = 401  #theta0,theta1,theta2
    cost = np.zeros(iterations) #error of every iteration
    for i in range(iterations):
        error = sigmoid(X*theta.T) - y
        for j in range(parameters):
            term = np.multiply(error, X[:,j]) 
            temp[0,j] = theta[0,j] - (alpha* np.sum(term))
        theta = temp
        cost[i] = computeCost(X,y,theta) 
    return theta,cost

In [59]:
def get_modified_y(y,i):
    y_mod=copy.deepcopy(y)
    for j in range(len(y)):
        if y_mod[j]==i:
            y_mod[j]=1
        else:
            y_mod[j]=0
    return y_mod


In [89]:
all_theta=np.matrix(np.zeros((10,401)))
for i in range(1,11):
    y_mod=get_modified_y(y,i)
    theta=np.matrix(np.zeros((1,401)))
    all_theta[i-1,:],b=gradientDescent(X,y_mod,theta,0.001,10000)

In [107]:
b  #-0.4054824309217161

array([-9.49789006e+02, -4.71655618e+02, -6.05826082e+01, ...,
       -4.05562574e-01, -4.05522498e-01, -4.05482431e-01])

In [105]:
all_theta.shape ##(10, 401)


(10, 401)

In [106]:
y_pred=sigmoid(X*all_theta.T)

In [93]:
y_pred.shape   #(5000, 10)

(5000, 10)

In [94]:
y[0]

matrix([[10]], dtype=uint8)

In [95]:
y_pred[499]

matrix([[3.21914853e-18, 4.01448517e-12, 1.86177175e-04, 6.21725484e-17,
         3.79588681e-11, 6.99739623e-20, 1.32410815e-05, 4.25450818e-10,
         7.81591056e-07, 9.99995202e-01]])

In [96]:
y[499]

matrix([[10]], dtype=uint8)

In [97]:
y_pred[4999].max()

0.286625167650522

In [98]:
y[4999].item()

9

In [99]:
h = np.argmax(y_pred, axis=1) + 1

In [100]:
count=0
for i in range(0,5000):
    if y[i,0]==h[i]:
        count+=1


In [109]:
count   ###4820

4820

In [110]:
y.shape

(5000, 1)

In [111]:
acc=(count*100)/len(X)

In [112]:
acc

96.4

In [113]:
y[1344].item()

2

In [114]:
np.argmax(y_pred[1546])+1

3

In [115]:
y_pred[50],y[50,0]

(matrix([[4.94544589e-27, 2.07074472e-03, 1.01262810e-07, 8.44210864e-12,
          7.84323791e-08, 4.56370063e-11, 1.65280112e-07, 1.10650223e-08,
          5.14519125e-07, 9.99999361e-01]]), 10)

In [116]:
y_pred[1500],y[1500,0]

(matrix([[9.40296419e-14, 2.80389527e-04, 9.95188928e-01, 3.35243028e-11,
          2.02690409e-05, 9.33281796e-20, 2.32040812e-14, 2.74605470e-03,
          1.57186474e-03, 1.45288050e-06]]), 3)

In [117]:
y_pred[1800],y[1800,0]

(matrix([[1.11804580e-05, 4.71184549e-06, 6.15110840e-01, 8.89546399e-05,
          9.03901515e-03, 4.32111201e-08, 6.71467083e-07, 1.44930017e-02,
          3.58238988e-03, 6.42331701e-08]]), 3)

In [118]:
y_pred[2500],y[2500,0]

(matrix([[3.73376261e-13, 2.58061817e-07, 2.57135403e-01, 9.02582627e-10,
          8.68119637e-01, 1.48237404e-09, 8.31228394e-07, 2.71164579e-06,
          1.33806978e-07, 3.55534680e-10]]), 5)

In [119]:
y_pred[4534],y[4534,0]

(matrix([[1.76726554e-08, 2.18395042e-04, 9.97188691e-08, 7.40585236e-04,
          2.10164299e-07, 3.26288877e-09, 9.29350292e-04, 1.53926123e-05,
          7.70067986e-01, 4.08317299e-09]]), 9)