In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.dtype

dtype('int32')

In [8]:
a.shape

(5,)

In [9]:
a.ndim

1

In [10]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [11]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
type(a)

numpy.ndarray

In [13]:
a.ndim

2

In [14]:
a=np.arange(15)

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
a=np.arange(0,20,0.5)

In [17]:
a

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [18]:
a.dtype

dtype('float64')

In [20]:
a.ndim

1

In [23]:
a=np.linspace(0,100,500)

In [24]:
a

array([  0.        ,   0.2004008 ,   0.4008016 ,   0.6012024 ,
         0.80160321,   1.00200401,   1.20240481,   1.40280561,
         1.60320641,   1.80360721,   2.00400802,   2.20440882,
         2.40480962,   2.60521042,   2.80561122,   3.00601202,
         3.20641283,   3.40681363,   3.60721443,   3.80761523,
         4.00801603,   4.20841683,   4.40881764,   4.60921844,
         4.80961924,   5.01002004,   5.21042084,   5.41082164,
         5.61122244,   5.81162325,   6.01202405,   6.21242485,
         6.41282565,   6.61322645,   6.81362725,   7.01402806,
         7.21442886,   7.41482966,   7.61523046,   7.81563126,
         8.01603206,   8.21643287,   8.41683367,   8.61723447,
         8.81763527,   9.01803607,   9.21843687,   9.41883768,
         9.61923848,   9.81963928,  10.02004008,  10.22044088,
        10.42084168,  10.62124248,  10.82164329,  11.02204409,
        11.22244489,  11.42284569,  11.62324649,  11.82364729,
        12.0240481 ,  12.2244489 ,  12.4248497 ,  12.62

In [25]:
from numpy import pi

In [26]:
a=np.arange(1,2*pi)

In [28]:
a

array([1.])

In [33]:
a=np.linspace(0,2*pi,100)

In [34]:
a

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [35]:
b=np.sin(a)

In [36]:
b

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [37]:
c=np.array([1,2,3,4],dtype='float64')

In [38]:
c

array([1., 2., 3., 4.])

In [39]:
d=np.zeros((3,4))

In [40]:
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
d=np.ones((3,4),dtype='int32')

In [42]:
d

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
d=np.arange(24).reshape(2,3,4)

In [45]:
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
d[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
d[0][2]

array([ 8,  9, 10, 11])

In [49]:
d[0][1]

array([4, 5, 6, 7])

In [50]:
d[0][0][1]

1

In [53]:
d[0,:,0]

array([0, 4, 8])

In [59]:
a=np.array([[1,1],[0,1]])

In [60]:
a

array([[1, 1],
       [0, 1]])

In [61]:
b=np.array([[2,3],[4,5]])

In [62]:
b

array([[2, 3],
       [4, 5]])

In [63]:
a+b

array([[3, 4],
       [4, 6]])

In [64]:
a-b

array([[-1, -2],
       [-4, -4]])

In [68]:
a*b    #for array multiplication

array([[2, 3],
       [0, 5]])

In [67]:
a@b  #for matrices multiplication

array([[6, 8],
       [4, 5]])

In [70]:
a.ndim,b.ndim

(2, 2)

In [72]:
A=np.matrix(a)


In [75]:
B=np.matrix(b)

In [76]:
A*B


matrix([[6, 8],
        [4, 5]])

In [77]:
A+B

matrix([[3, 4],
        [4, 6]])

In [82]:
np.multiply(A,B)  #for multiplication like array

matrix([[2, 3],
        [0, 5]])

In [84]:
a.dot(b)  #for array multiply like matrix if both are ndArray

array([[6, 8],
       [4, 5]])

In [86]:
a.sum(),a.min(),a.max()

(3, 0, 1)

In [88]:
b

array([[2, 3],
       [4, 5]])

In [91]:
b.sum(axis=1) #rows-wise sum 

array([5, 9])

b.min(axis=1)

In [92]:
b.min(axis=1)  #rows-wise min

array([2, 4])

In [93]:
c=np.ravel(a) #to convert in 1D

In [94]:
c

array([1, 1, 0, 1])

In [99]:
e=np.power(b,2)

In [100]:
e

array([[ 4,  9],
       [16, 25]], dtype=int32)

In [104]:
e[:,:1]  #when to print slices in matrix

array([[ 4],
       [16]], dtype=int32)

In [105]:
A.T  #transpose Of Matrix

matrix([[1, 0],
        [1, 1]])

In [106]:
import pandas as pd

In [107]:
data=pd.read_csv("E:\Python\PracticleData\data1.txt", names=["population","Profit"])

In [108]:
data

population    Profit
0       6.1101  17.59200
1       5.5277   9.13020
2       8.5186  13.66200
3       7.0032  11.85400
4       5.8598   6.82330
..         ...       ...
92      5.8707   7.20290
93      5.3054   1.98690
94      8.2934   0.14454
95     13.3940   9.05510
96      5.4369   0.61705

[97 rows x 2 columns]

In [113]:
data.head()


population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [112]:
data.tail()

population   Profit
92      5.8707  7.20290
93      5.3054  1.98690
94      8.2934  0.14454
95     13.3940  9.05510
96      5.4369  0.61705

In [114]:
data.describe()

population     Profit
count   97.000000  97.000000
mean     8.159800   5.839135
std      3.869884   5.510262
min      5.026900  -2.680700
25%      5.707700   1.986900
50%      6.589400   4.562300
75%      8.578100   7.046700
max     22.203000  24.147000